module.exports = [
    // Palabras clave relacionadas con contenido para adultos
    'porn', 'pornography', 'sex', 'sexy', 'nude', 'naked', 'adult', 'xxx', 'erotic',
    'vagina', 'penis', 'boobs', 'butt', 'ass', 'dick', 'pussy', 'cum', 'ejaculation',
    'orgasm', 'masturbation', 'fetish', 'pornhub', 'redtube', 'xvideos', 'youporn',
    'sexvideos', 'adultvideos', 'hardcore', 'softcore', 'adultmovies', 'sexmovies',
    'adultfilm', 'pornfilm', 'strip', 'striptease', 'camgirl', 'camboy', 'sexchat',
    'sexcam', 'adultchat', 'sexsite', 'pornsite', 'dirty', 'kinky', 'slut', 'whore',
    'prostitute', 'escort', 'brothel', 'pimp', 'sextoy', 'vibrator', 'dildo', 'lube',
    'bukkake', 'fisting', 'anal', 'rimming', 'orgy', 'threesome', 'bisexual', 'gay',
    'lesbian', 'hentai', 'bdsm', 'bondage', 'dominatrix', 'submissive', 'dominant',
    'swinger', 'adultentertainment', 'porno', 'x-rated', 'adultstore', 'pornstore',
    'erotica', 'adultfilm', 'eroticfilm', 'adultgames', 'porngames', 'nudity', 'sexually',
    'explicit', 'taboo', 'nudes', 'camshow', 'liveporn', 'nudeart', 'sensual', 'tease',
    'adultcontent', 'dirtytalk', 'sexytime', 'eroticstory', 'pornstory', 'sexstory',
    'adultweb', 'sexdoll', 'sexworker', 'escortservice', 'sexshop', 'sexstore',
    'bdsm', 'fetish', 'bondage', 'roleplay', 'submissive', 'dominant', 'dominatrix',
    'whips', 'leather', 'handcuffs', 'collar', 'gag', 'spank', 'punishment', 'discipline',
    'slave', 'master', 'mistress', 'swinging', 'orgasm', 'climax', 'sexy', 'sensual',
    'sexually', 'explicit', 'taboo', 'nudity', 'dirty', 'kinky', 'erotic', 'adultfilm',
    'fetish', 'bdsm', 'bondage', 'roleplay', 'kink', 'adultart', 'adultvideos', 'adultcontent',
    'nudephotos', 'nakedphotos', 'adultphotos', 'dirtyphotos', 'sexyphotos', 'pornphotos',
    'adultclips', 'pornclips', 'dirtyclips', 'sexclips', 'eroticclips', 'nudeclips', 'swingers',
    'desnudez',
    'voyeur',
    'nudismo',
    'perversión',
    'pornstars',
    'exhibicionista',
    'estimulador',
    'sadomasoquista',
    'porn',
    'pornography',
    'erotic',
    'sex',
    'sensual',
    'nude',
    'genitals',
    'penis',
    'vagina',
    'breasts',
    'boobs',
    'butt',
    'ass',
    'cock',
    'dick',
    'penetration',
    'masturbation',
    'ejaculation',
    'semen',
    'clitoris',
    'orgasm',
    'suck',
    'blowjob',
    'fellatio',
    'cunnilingus',
    'gangbang',
    'orgy',
    'incest',
    'bestiality',
    'zoophilia',
    'pedophilia',
    'rape',
    'sadism',
    'masochism',
    'BDSM',
    'slavery',
    'sado',
    'submission',
    'dominance',
    'fetish',
    'fantasy',
    'hardcore',
    'softcore',
    'camgirl',
    'webcam',
    'exhibitionism',
    'voyeurism',
    'striptease',
    'prostitution',
    'escort',
    'transvestite',
    'transsexual',
    'shemale',
    'orgasmic',
    'arousing',
    'hentai',
    'lolita',
    'amateur',
    'milf',
    'cougar',
    'virgin',
    'lingerie',
    'lubricant',
    'vibrator',
    'dildo',
    'sex toys',
    'aphrodisiac',
    'brothel',
    'lust',
    'fornication',
    'threesome',
    'moaning',
    'fetishism',
    'sadomasochism',
    'bondage',
    'dominatrix',
    'whip',
    'handcuffs',
    'fantasies',
    'xxx videos',
    'swingers',
    'nudity',
    'voyeur',
    'nudism',
    'perversion',
    'pornstars',
    'exhibitionist',
    'stimulator',
    'sadomasochist',
    'taboo',
    'smut',
    'explicit',
    'kink',
    'raunchy',
    'hardcore porn',
    'adult entertainment',
    'naughty',
    'porno',
    'pornografie',
    'erotik',
    'sex',
    'sinnlich',
    'nackt',
    'genitalien',
    'penis',
    'vagina',
    'brüste',
    'titten',
    'hintern',
    'arsch',
    'schwanz',
    'eindringen',
    'masturbation',
    'ejakulation',
    'sperma',
    'klitoris',
    'orgasmus',
    'blasen',
    'blowjob',
    'fellatio',
    'cunnilingus',
    'gangbang',
    'orgie',
    'inzest',
    'bestialität',
    'zoophilie',
    'pädophilie',
    'vergewaltigung',
    'sadismus',
    'masochismus',
    'BDSM',
    'sklaverei',
    'sado',
    'unterwerfung',
    'dominanz',
    'fetisch',
    'fantasie',
    'hardcore',
    'softcore',
    'camgirl',
    'webcam',
    'exhibitionismus',
    'voyeurismus',
    'striptease',
    'prostitution',
    'escort',
    'transvestit',
    'transsexuell',
    'shemale',
    'orgasmisch',
    'erregend',
    'hentai',
    'lolita',
    'amateur',
    'milf',
    'puma',
    'jungfrau',
    'unterwäsche',
    'gleitmittel',
    'vibrator',
    'dildo',
    'sexspielzeug',
    'aphrodisiakum',
    'bordell',
    'lust',
    'hurerei',
    'dreier',
    'stöhnen',
    'fetischismus',
    'sadomasochismus',
    'bondage',
    'dominatrix',
    'peitsche',
    'handschellen',
    'phantasien',
    'xxx videos',
    'swinger',
    'nacktheit',
    'voyeur',
    'nudismus',
    'perversion',
    'pornostars',
    'exhibitionist',
    'stimulator',
    'sadomasochist',
    'tabu',
    'schmutz',
    'explizit',
    'pervers',
    'kinky',
    'hardcore-pornografie',
    'erwachsenenunterhaltung',
    'unartig',
    'порно',
    'порнография',
    'эротика',
    'секс',
    'похоть',
    'голый',
    'гениталии',
    'пенис',
    'вагина',
    'грудь',
    'сиськи',
    'задница',
    'жопа',
    'член',
    'проникновение',
    'мастурбация',
    'эякуляция',
    'сперма',
    'клитор',
    'оргазм',
    'минет',
    'оральный секс',
    'кунилингус',
    'групповуха',
    'орги',
    'инцест',
    'зоофилия',
    'педофилия',
    'изнасилование',
    'садизм',
    'мазохизм',
    'БДСМ',
    'рабство',
    'сабмиссив',
    'доминирование',
    'фетиш',
    'фантазия',
    'хардкор',
    'мягкое порно',
    'камгёрл',
    'вебкам',
    'эксгибиционизм',
    'вуайеризм',
    'стриптиз',
    'проституция',
    'эскорт',
    'трансвестит',
    'транссексуал',
    'с shemale',
    'оргазмический',
    'возбуждение',
    'хентай',
    'лолита',
    'любительское',
    'милф',
    'кугуар',
    'девственница',
    'нижнее белье',
    'лубрикант',
    'вибратор',
    'дилдо',
    'секс-игрушка',
    'афродизиак',
    'бордель',
    'страсть',
    'блуд',
    'тройничок',
    'стон',
    'фетишизм',
    'садомазохизм',
    'связывание',
    'госпожа',
    'плеть',
    'наручники',
    'фантазии',
    'xxx видео',
    'свингер',
    'нагота',
    'вуайер',
    'натуризм',
    'извращение',
    'порнозвезда',
    'эксгибиционист',
    'стимулятор',
    'садомазохист',
    'табу',
    'грязь',
    'откровенный',
    'извращенный',
    'кинки',
    'хардкор-порнография',
    'развлечения для взрослых',
    'непослушный',
    'porno',
    'pornographie',
    'érotisme',
    'sexe',
    'luxure',
    'nu',
    'génital',
    'pénis',
    'vagin',
    'seins',
    'nichons',
    'fesses',
    'cul',
    'queue',
    'pénétration',
    'masturbation',
    'éjaculation',
    'sperme',
    'clitoris',
    'orgasme',
    'fellation',
    'sexe oral',
    'cunnilingus',
    'partouze',
    'orgie',
    'inceste',
    'zoophilie',
    'pédophilie',
    'viol',
    'sadisme',
    'masochisme',
    'BDSM',
    'esclavage',
    'soumission',
    'domination',
    'fétiche',
    'fantasme',
    'hardcore',
    'porno soft',
    'camgirl',
    'webcam',
    'exhibitionnisme',
    'voyeurisme',
    'strip-tease',
    'prostitution',
    'escort',
    'travesti',
    'transsexuel',
    'shemale',
    'excitation',
    'hentai',
    'lolita',
    'amateur',
    'MILF',
    'cougar',
    'vierge',
    'lingerie',
    'lubrifiant',
    'vibromasseur',
    'godemichet',
    'jouet sexuel',
    'aphrodisiaque',
    'bordel',
    'passion',
    'débauche',
    'plan à trois',
    'gémissement',
    'fétichisme',
    'sadomasochisme',
    'ligotage',
    'maîtresse',
    'fouet',
    'menottes',
    'fantasmes',
    'vidéo xxx',
    'échangisme',
    'nudité',
    'voyeur',
    'naturisme',
    'perversion',
    'star du porno',
    'exhibitionniste',
    'stimulateur',
    'sadomasochiste',
    'tabou',
    'cochon',
    'ouvertement',
    'pervers',
    'kinky',
    'pornographie hardcore',
    'divertissement pour adultes',
    'coquin',

    // Nombres de sitios web para adultos comunes (sin extensiones)
    'pornhub', 'xvideos', 'redtube', 'youporn', 'xnxx',
    'tube8', 'tnaflix', 'spankbang', 'porn300', 'brazzers',
    'xhamster', 'hentaistream', 'youjizz', 'porn', 'tube8',
    'hentaihaven', 'sex', 'adultfriendfinder', 'hentaifoundry',
    'livejasmine', 'chaturbate', 'cam4', 'myfreecams', 'streamate',
    'bongacams', 'shesfreaky', 'onlyfans', 'livesex', 'pornhd',
    'tushy', 'xfreecam', 'mydirtyhobby', 'fapdu', 'cambro', 'hcl',
    'livestream', 'hookup', 'sexyme', 'hotbabes', 'nakedbabes',
    'sexysites', 'hotgals', 'adulttube', 'eroticplanet', 'adultworld',
    'horny', 'sexyfun', 'adultland', 'adultspot', 'adultforum',
    'sexforums', 'pornforums', 'sexvideos', 'adultvids', 'dirtyvideos',
    'nudevideos', 'nudesites', 'adultcontent', 'eroticvideos', 'eroticchat',
    'adultchatrooms', 'adultstreams', 'livecams', 'camshows', 'webcamshows',
    'nakedshows', 'pornshows', 'adultshows', 'sexshows', 'adultvideo',
    'sexvideo', 'eroticvideo', 'nakedvideo', 'camvideo', 'pornchannel',
    'adultchannel', 'sextv', 'nakedtv', 'adultstreaming', 'pornstreaming',
    'hotsex', 'dirtypics', 'xxxvideos', 'adultpics', 'nudeart', 'sexyart',
    'sexart', 'nakedart', 'adultsites', 'pornsites', 'sexsites', 'adultlinks',
    'pornlinks', 'sexylinks', 'adultcontent', 'porncontent', 'sexcontent',
    'dirtycontent', 'kinkycontent', 'adultnetwork', 'pornnetwork', 'sexnetwork',
    'adultmedia', 'pornmedia', 'sexmedia', 'dirtymedia', 'eroticmedia',
    'sexfilms', 'adultfilms', 'dirtyfilms', 'pornfilms', 'eroticfilms',
    'nakedfilms', 'hotfilms', 'sexmovies', 'adultmovies', 'eroticmovies',
    'dirtymovies', 'pornmovies', 'x-ratedmovies', 'sexvideos', 'pornvideos',
    'adultvideos', 'dirtyvideos', 'eroticvideos', 'nakedvideos'
];