module.exports = [
    // Palabras clave relacionadas con contenido para adultos
    'porn', 'pornography', 'sex', 'sexy', 'nude', 'naked', 'adult', 'xxx', 'erotic',
    'vagina', 'penis', 'boobs', 'butt', 'ass', 'dick', 'pussy', 'cum', 'ejaculation',
    'orgasm', 'masturbation', 'fetish', 'pornhub', 'redtube', 'xvideos', 'youporn',
    'sexvideos', 'adultvideos', 'hardcore', 'softcore', 'adultmovies', 'sexmovies',
    'adultfilm', 'pornfilm', 'strip', 'striptease', 'camgirl', 'camboy', 'sexchat',
    'sexcam', 'adultchat', 'sexsite', 'pornsite', 'dirty', 'kinky', 'slut', 'whore',
    'prostitute', 'escort', 'brothel', 'pimp', 'sextoy', 'vibrator', 'dildo', 'lube',
    'bukkake', 'fisting', 'anal', 'rimming', 'orgy', 'threesome', 'bisexual', 'gay',
    'lesbian', 'hentai', 'bdsm', 'bondage', 'dominatrix', 'submissive', 'dominant',
    'swinger', 'adultentertainment', 'porno', 'x-rated', 'adultstore', 'pornstore',
    'erotica', 'adultfilm', 'eroticfilm', 'adultgames', 'porngames', 'nudity', 'sexually',
    'explicit', 'taboo', 'nudes', 'camshow', 'liveporn', 'nudeart', 'sensual', 'tease',
    'adultcontent', 'dirtytalk', 'sexytime', 'eroticstory', 'pornstory', 'sexstory',
    'adultweb', 'sexdoll', 'sexworker', 'escortservice', 'sexshop', 'sexstore',
    'bdsm', 'fetish', 'bondage', 'roleplay', 'submissive', 'dominant', 'dominatrix',
    'whips', 'leather', 'handcuffs', 'collar', 'gag', 'spank', 'punishment', 'discipline',
    'slave', 'master', 'mistress', 'swinging', 'orgasm', 'climax', 'sexy', 'sensual',
    'sexually', 'explicit', 'taboo', 'nudity', 'dirty', 'kinky', 'erotic', 'adultfilm',
    'fetish', 'bdsm', 'bondage', 'roleplay', 'kink', 'adultart', 'adultvideos', 'adultcontent',
    'nudephotos', 'nakedphotos', 'adultphotos', 'dirtyphotos', 'sexyphotos', 'pornphotos',
    'adultclips', 'pornclips', 'dirtyclips', 'sexclips', 'eroticclips', 'nudeclips', 'swingers',
    'desnudez',
    'voyeur',
    'nudismo',
    'perversión',
    'pornstars',
    'exhibicionista',
    'estimulador',
    'sadomasoquista',

    // Nombres de sitios web para adultos comunes (sin extensiones)
    'pornhub', 'xvideos', 'redtube', 'youporn', 'xnxx',
    'tube8', 'tnaflix', 'spankbang', 'porn300', 'brazzers',
    'xhamster', 'hentaistream', 'youjizz', 'porn', 'tube8',
    'hentaihaven', 'sex', 'adultfriendfinder', 'hentaifoundry',
    'livejasmine', 'chaturbate', 'cam4', 'myfreecams', 'streamate',
    'bongacams', 'shesfreaky', 'onlyfans', 'livesex', 'pornhd',
    'tushy', 'xfreecam', 'mydirtyhobby', 'fapdu', 'cambro', 'hcl',
    'livestream', 'hookup', 'sexyme', 'hotbabes', 'nakedbabes',
    'sexysites', 'hotgals', 'adulttube', 'eroticplanet', 'adultworld',
    'horny', 'sexyfun', 'adultland', 'adultspot', 'adultforum',
    'sexforums', 'pornforums', 'sexvideos', 'adultvids', 'dirtyvideos',
    'nudevideos', 'nudesites', 'adultcontent', 'eroticvideos', 'eroticchat',
    'adultchatrooms', 'adultstreams', 'livecams', 'camshows', 'webcamshows',
    'nakedshows', 'pornshows', 'adultshows', 'sexshows', 'adultvideo',
    'sexvideo', 'eroticvideo', 'nakedvideo', 'camvideo', 'pornchannel',
    'adultchannel', 'sextv', 'nakedtv', 'adultstreaming', 'pornstreaming',
    'hotsex', 'dirtypics', 'xxxvideos', 'adultpics', 'nudeart', 'sexyart',
    'sexart', 'nakedart', 'adultsites', 'pornsites', 'sexsites', 'adultlinks',
    'pornlinks', 'sexylinks', 'adultcontent', 'porncontent', 'sexcontent',
    'dirtycontent', 'kinkycontent', 'adultnetwork', 'pornnetwork', 'sexnetwork',
    'adultmedia', 'pornmedia', 'sexmedia', 'dirtymedia', 'eroticmedia',
    'sexfilms', 'adultfilms', 'dirtyfilms', 'pornfilms', 'eroticfilms',
    'nakedfilms', 'hotfilms', 'sexmovies', 'adultmovies', 'eroticmovies',
    'dirtymovies', 'pornmovies', 'x-ratedmovies', 'sexvideos', 'pornvideos',
    'adultvideos', 'dirtyvideos', 'eroticvideos', 'nakedvideos'
];